/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error-container': 'var(--on-error-container)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'inverse-on-surface': 'var(--inverse-on-surface)',
        'tertiary': 'var(--tertiary)',
        'surface-container-low': 'var(--surface-container-low)',
        'tertiary-fixed-dim': 'var(--tertiary-fixed-dim)',
        'surface': 'var(--surface)',
        'on-tertiary-fixed-variant': 'var(--on-tertiary-fixed-variant)',
        'on-secondary-fixed': 'var(--on-secondary-fixed)',
        'primary-fixed-dim': 'var(--primary-fixed-dim)',
        'outline': 'var(--outline)',
        'surface-tint': 'var(--surface-tint)',
        'on-primary': 'var(--on-primary)',
        'inverse-primary': 'var(--inverse-primary)',
        'surface-dim': 'var(--surface-dim)',
        'on-tertiary-fixed': 'var(--on-tertiary-fixed)',
        'on-secondary-fixed-variant': 'var(--on-secondary-fixed-variant)',
        'outline-variant': 'var(--outline-variant)',
        'secondary-container': 'var(--secondary-container)',
        'secondary': 'var(--secondary)',
        'error': 'var(--error)',
        'inverse-surface': 'var(--inverse-surface)',
        'on-secondary': 'var(--on-secondary)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'error-container': 'var(--error-container)',
        'on-background': 'var(--on-background)',
        'on-primary-container': 'var(--on-primary-container)',
        'on-surface': 'var(--on-surface)',
        'primary-fixed': 'var(--primary-fixed)',
        'primary-container': 'var(--primary-container)',
        'primary': 'var(--primary)',
        'on-primary-fixed': 'var(--on-primary-fixed)',
        'surface-variant': 'var(--surface-variant)',
        'on-error': 'var(--on-error)',
        'secondary-fixed-dim': 'var(--secondary-fixed-dim)',
        'background': 'var(--background)',
        'surface-bright': 'var(--surface-bright)',
        'surface-container-high': 'var(--surface-container-high)',
        'surface-container': 'var(--surface-container)',
        'on-tertiary': 'var(--on-tertiary)',
        'on-secondary-container': 'var(--on-secondary-container)',
        'tertiary-container': 'var(--tertiary-container)',
        'on-surface-variant': 'var(--on-surface-variant)',
        'secondary-fixed': 'var(--secondary-fixed)',
        'on-tertiary-container': 'var(--on-tertiary-container)',
        'on-primary-fixed-variant': 'var(--on-primary-fixed-variant)',
        'tertiary-fixed': 'var(--tertiary-fixed)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '16px',
        'gutter': '24px',
        'glass-padding': '24px',
        'container-padding': '32px',
        'unit': '4px',
        'stack-lg': '32px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'float-fast': 'float 3s ease-in-out infinite',
        'card-entrance': 'cardEntrance 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        cardEntrance: {
          '0%': { opacity: '0', transform: 'scale(0.95) translateY(10px)' },
          '100%': { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
